name: Compile Translations

on:
  push:
    paths:
      - 'translations/**/*.po'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Babel
      run: |
        pip install flask_babel

    - name: Compile translations
      run: |
        pybabel compile -d translations

    - name: Commit compiled files
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add translations/**/*.mo
        git commit -m "Compiled translations"
        git push
